### ISSUE TITLE
Warning: More than one copy of gmp already loaded, using the 1st one

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/HomalgProject.jl#5]
@fingolfin: Why do I get this warning when `using HomalgProject` but not when `using Oscar` although both import `GAP` and `Singular`.

```julia
julia> using HomalgProject
┌ Warning: More than one copy of gmp already loaded, using the 1st one
└ @ LoadFlint ~/.julia/packages/LoadFlint/42zpR/src/LoadFlint.jl:40

julia>
```

**Comment by fingolfin** [comment]
This warning is generated by LoadFlint when, well, multiple copies of GMP are loaded *before* LoadFlint. So it depends on the order in which things are loaded.

It's harmless but perhaps a bit too scary. We already turned it from an error into a warning; perhaps we should go further and silence it by default? @fieker? Might be worth to first look into why it's being shown now, though

**Comment by fieker** [comment]
On Thu, Apr 23, 2020 at 04:34:20PM -0700, Max Horn wrote:
> This warning is generated by LoadFlint when, well, multiple copies of GMP are loaded *before* LoadFlint. So it depends on the order in which things are loaded.
> 
> It's harmless but perhaps a bit too scary. We already turned it from an error into a warning; perhaps we should go further and silence it by default? @fieker? Might be worth to first look into why it's being shown now, though
> 
I don't thin it is neccessarily harmless. Problem still is that we are
using libantic which is using libflint which is using libgmp
For the memory management it is kind of important that the various
libraries are consistent wrt. alloc/free and such.
Aparently I do not control which gmp is called in the end - unless I
call it directly.

**Comment by mohamed-barakat** [comment]
> This warning is generated by LoadFlint when, well, multiple copies of GMP are loaded _before_ LoadFlint. So it depends on the order in which things are loaded.

@fingolfin: So is there a way to influence the order of loading?

And if yes, the risk would probably still exist of having multiple copies of GMP, right?

@fieker: Phrased differently, does the problem still exist with Oscar, at by the accidental order of loading you don't get the warning?

> It's harmless but perhaps a bit too scary. We already turned it from an error into a warning; perhaps we should go further and silence it by default? @fieker? Might be worth to first look into why it's being shown now, though

**Comment by fingolfin** [comment]
@mohamed-barakat can you please trigger the warning, and then tell us the output of this command so we can see where those copies come from:
`using Libdl ; filter(x->occursin("libgmp", x),  dllist())`

You can influence the order by e.g. doing `using Loadflint` first before loading anything else. BUT that won't help if there are already two GMPs loaded by that point.

@fieker The reason I am not so worried about it is an empirical one: every Julia project out there using GMP would otherwise experience problems related to it. Not sure why it works, but it does, and so I don't bother investigating it further (for now).

That said, let's first see where Mohamed's GMPs all come from.

**Comment by mohamed-barakat** [comment]
> @mohamed-barakat can you please trigger the warning, and then tell us the output of this command so we can see where those copies come from:
> `using Libdl ; filter(x->occursin("libgmp", x), dllist())`

```julia
julia> using Libdl ; filter(x->occursin("libgmp", x), dllist())
1-element Array{String,1}:
 "/Applications/Julia-1.4.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib"
```

**Comment by mohamed-barakat** [comment]
When switching to GAP.jl#master the waring vanishes :)

**Comment by fieker** [comment]
On Fri, Apr 24, 2020 at 01:33:31AM -0700, Mohamed Barakat wrote:
> > This warning is generated by LoadFlint when, well, multiple copies of GMP are loaded _before_ LoadFlint. So it depends on the order in which things are loaded.
> 
> @fingolfin: So is there a way to influence the order of loading?
> 
> And if yes, the risk would probably still exist of having multiple copies of GMP, right?
> 
> @fieker: Phrased differently, does the problem still exist with Oscar, at by the accidental order of loading you don't get the warning?
I don't know. Within Oscar, the problem shuld be history, that was
LoadFlint.jl, problme is/was in Oscar we do
using Nemo,Singular,Polymake
the actual order in Oscar does not matter as Julia seems to re-order
anyway.
Outside of Julia the order might matter. The hope is that eventually the
artifacts should avercome this as then the c-libraries will become more
package like....

**Comment by mohamed-barakat** [comment]
Many thanks for your reply. Unless the issue pops up again I will close this issue for now.
